billeterie_assos/billeterie_assos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls')), 
    path('', include('shop.urls')),
    url(r'', include('social_django.urls' ,namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billeterie_assos/event/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from social_django.urls import urlpatterns as social_django_urls
from shop import views as com_views
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('assos/mine/', login_required(views.MyAssosView.as_view(), login_url='login'), name='my_assos'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('cri_epita.urls', namespace="cri")),
    path('assos/<int:pk>', views.AssosDetailView.as_view(), name='asso_detail'),
    path('assos/', views.AssosView.as_view(), name='assos'),
    path('event/', views.EventListView.as_view(), name='events'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('upcomming_events/', views.Upcomming_Events, name='upcomming_events'),
    path('assos/delete/<int:pk>', views.AssosDelete.as_view(), name='assos_delete'),
    path('assos/<int:asso_pk>/delete/member/<int:pk>', views.MemberDelete.as_view(), name='delete_member'),
    path('assos/<int:asso_pk>/manager/add/<int:pk>', views.ManagerCreate.as_view(), name='add_manager'),
    path('assos/<int:asso_pk>/delete/manager/<int:pk>', views.ManagerDelete.as_view(), name='delete_manager'),
    path('shop/', com_views.index_shop, name='shop'),
    path('product/<int:product_id>/', com_views.show_product, name='product_detail'),
    path('search/', views.search, name='search'),
    path('assos/create/', permission_required('event.add_association', login_url='login')(views.AssosCreateView.as_view()), name='asso_creation'),
    path('assos/event/create/', views.EventCreateGeneralView.as_view(), name='general_event_creation'),
    path('assos/event/create/<int:asso>', views.EventCreateView.as_view(), name='event_creation'),
    path('event/delete/<int:pk>', views.EventDelete.as_view(), name='event_delete'),
    path('event/cancelable/<int:pk>', views.EventCancelable.as_view(), name='make_cancelable'),
    path('event/cancel/<int:pk>', views.EventCancel.as_view(), name='event_cancel'),
    path('assos/president/add/<int:pk>', permission_required('event.add_president', login_url='login')(views.PresidentCreate.as_view()), name='add_president'),
    path('event/<int:event_pk>/staff/delete/<int:pk>', views.StaffDelete.as_view(), name='staff_delete'),
    path('event/approve/<int:pk>', views.EventApprove.as_view(), name='event_approve'),
    path('event/validate/<int:pk>', views.EventValidate.as_view(), name='event_validate'),
    path('event/pending/<int:pk>', views.EventDisapprove.as_view(), name='event_disapprove'),
    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),
]

billeterie_assos/shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    
    path('shop', views.index_shop, name='index_shop'),
    path('product/<int:product_id>/',
        views.show_product, name='product_detail'),
    path('cart/', views.show_cart, name='show_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('info/', views.info, name='info'),
]

billeterie_assos/templates/association_new.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="basic-block">
    <h1 style="font-family:'Courier New', Courier, monospace; font-weight:bolder; color:#100b2c; text-transform: uppercase; margin:10px; margin-bottom: 30px;">Assos Creation</h1>
    <form style="margin-left:50px;" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class= "btn btn-secondary" type="submit" value="Create">
    </form>
</div>
{% endblock content %}

billeterie_assos/templates/assos_detail.html
{% extends "base.html" %}
{% load static %}
{% load guardian_tags %}

{%block content %}
    {% get_obj_perms user for object as "assos_perms" %}
    <div style="font-size:1.1rem;"class="container basic-block">
        <h1 style="font-family:'Courier New', Courier, monospace; font-weight:bolder; color:#100b2c; text-transform: uppercase; margin:10px; margin-bottom: 30px;">{{object.name}}</h1>
        {% if object.url != None %}
            <a href={{object.url}}>Go to their website</a>
        {% endif %}
        {% if president %}
        <div class="row">
            <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                <p><b>Current president</b> : {{president.user.username}}</p>
                {% else %}
                <p><b>President</b> : Anonymous</p>
                {% endif %}
                <p><b>Membres du bureau</b> :</p>
                <ul style="">
                    {% for manager in managers %}
                    <li>{{manager.user.username}}
                    {% if "manage_manager" in assos_perms or perms.event.manage_manager %}
                        <a style="margin-left:20px; color:#6351ce; font-size:0.8rem;" class="confirm" href="{% url 'event:delete_manager' asso_pk=object.pk pk=manager.pk %}">Retograde to member</a>
                        {% endif %}
                        {% if perms.event.add_president %}
                        <a style="margin-left:20px; color:#6351ce; font-size:0.8rem;" class="confirm" href="{% url 'event:add_president' manager.pk %}">Switch with current President</a>
                    {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                {% if "manage_member" in assos_perms or perms.event.manage_member %}
                <p><b>Membres </b> :<button style="margin-left:20px;" class="btn btn-outline-success" onclick="display('add_members')">Add Members</button></p>
                <form id="add_members" style="display: none;" action="{{object.get_absolute_url}}" method="POST">
                {% csrf_token %}
                {{form}}
                <input type="submit" value="Add members">
                </form>
                {% endif %}
                <ul>
                    {% for member in members %}
                        <li>{{member.user.username}}
                        {% if "manage_member" in assos_perms or perms.event.manage_member %}
                            <a style="margin-left:20px; color:#6351ce; font-size:0.8rem;" class="confirm" href="{% url 'event:delete_member' asso_pk=object.pk pk=member.pk %}">Remove</a>
                        {% endif %}
                        {% if "manage_manager" in assos_perms or perms.event.manage_manger %}
                            <a style="margin-left:20px; color:#6351ce; font-size: 0.8rem;" class="confirm" href="{% url 'event:add_manager' pk=member.pk asso_pk=object.pk %}">Promote to manager</a>
                        {% endif %}
                        </li>
                    {% endfor %}
                </ul>
                <h4><b style="text-decoration: underline;">Events</b> :</h4>
                <div style="margin-left:50px;">
                    {% if "create_event" in assos_perms or perms.event.create_event %}
                    <a style="margin:15px;" href="{% url 'event:event_creation' asso=object.pk%}">
                    <button style="margin-top:20px;" class="btn btn-outline-success">Create an event</button>
                    </a>
                    {% endif %}
                    <p style="margin-top:20px;"><b>Ongoing events</b> :</p>
                    <ul>
                        {% for event in ongoing_events %}
                        <li><a style="color:#6351ce; "href="{{event.get_absolute_url}}">{{event.title}}</a></li>
                        {% endfor %}
                    </ul>
                    <p><b>Future events</b> :</p>
                    <ul>
                        {% for event in future_events %}
                        <li><a style="color:#6351ce; "href="{{event.get_absolute_url}}">{{event.title}}</a></li>
                        {% endfor %}
                    </ul> 
                    {% if "delete_association" in assos_perms or perms.event.delete_association %}
                    <form action="{% url 'event:assos_delete' object.pk %}" method="POST">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" class="confirm" value="Delete" />
                    </form>
                    {% endif %}
                </div>
            </article>
            <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                <img src="{% static "img/assos_detail_img.png"%}" style="
                    opacity: 0.9;
                    height:80%; 
                    width:80%;
                    border-radius: 10px;
                ">
            </article>
        </div>
    </div>
{% endblock content %}

billeterie_assos/templates/assos_list.html
{% extends "base.html" %}
{% load static %}
{% load guardian_tags %}

{%block content %}    
    <div class="container basic-block">
        <h1 style="
            font-family: 'Courier New', Courier, monospace;
            font-weight:bold;
        ">Associations List</h1>
        <div class="row">
            <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                {% if perms.event.add_association %}
                <a class="btn btn-danger" style="margin-bottom: 15px;" href="{% url 'event:asso_creation' %}">Create an association</a>
                {% endif %}
                {% if assos %}
                <ul style="
                    font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
                ">
                {% for asso in assos %}
                    {% get_obj_perms user for asso as "asso_perms" %}
                    <li style="list-style-type: none; 
                            margin-bottom: 5px;
                    ">
                        <a style="
                            color:black;
                            opacity: 0.8;
                            " href="{{asso.get_absolute_url}}">{{ asso.name }}</a>
                    {% if "delete_association" in asso_perms or perms.event.delete_association %}
                    <a style="
                            margin-left:10px;
                        " href="{% url 'event:assos_delete' asso.pk %}">Delete
                    </a>
                    {% endif %}
                    </li>
                {% endfor %}
                </ul>
                {% else %}
                <p> no assos </p>
                {% endif %}
            </article>
            <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                <img src="{% static "img/assos_list_img.jpg"%}" style="
                    opacity: 0.9;
                    height:100%; 
                    width:100%;
                    border-radius: 10px;
                ">
            </article>
        </div>
    </div>
{% endblock content %}

billeterie_assos/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    
    <title>{% block title %}EPITA BILLETERIE{% endblock title %}</title>
</head>

<body>
    <div>{% block navbar %}{% include "includes/mainmenu.html" %}{% endblock navbar %}</div>
    <main class="container">
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </main>
    <div>
    {% block footer %}
        <!-- Footer -->
    <footer class="page-footer font-small unique-color-dark">


          <div class="container page-footer-top">
            <!-- Grid row-->
            <div class="row py-4 d-flex align-items-center">

              <!-- Grid column -->
              <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
                <h6 class="mb-0">Get connected with us on social networks!</h6>
              </div>
              <!-- Grid column -->

              <!-- Grid column -->
              <div class="col-md-6 col-lg-7 text-center text-md-right">

                <!-- Facebook -->
                <a class="fb-ic">
                  <i class="fab fa-facebook-f white-text mr-4"> </i>
                </a>
                <!-- Twitter -->
                <a class="tw-ic">
                  <i class="fab fa-twitter white-text mr-4"> </i>
                </a>
                <!-- Google +-->
                <a class="gplus-ic">
                  <i class="fab fa-google-plus-g white-text mr-4"> </i>
                </a>
                <!--Linkedin -->
                <a class="li-ic">
                  <i class="fab fa-linkedin-in white-text mr-4"> </i>
                </a>
                <!--Instagram-->
                <a class="ins-ic">
                  <i class="fab fa-instagram white-text"> </i>
                </a>

              </div>
              <!-- Grid column -->

            </div>
            <!-- Grid row-->

          </div>

        <!-- Footer Links -->
        <div class="container text-center text-md-left mt-5 footer-size">

          <!-- Grid row -->
          <div class="row mt-3">

            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

              <!-- Content -->
              <h6 class="text-uppercase font-weight-bold">Billeterie EPITA</h6>
              <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
              <img src="{% static "img/logo-epita.png" %}" style="height:80%; width:80%;">


            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

              <!-- Links -->
              <h6 class="text-uppercase font-weight-bold">Useful links</h6>
              <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
              <p>
                <a target="_blank" href="https://www.epita.fr/">EPITA</a>
              </p>
              <p>
                <a target="_blank" href="https://www.facebook.com/epita/">Facebook Page</a>
              </p>
              <p>
                <a target="_blank" href="https://twitter.com/epita">Twitter Page</a>
              </p>
              <p>
                <a target="_blank" href="https://cri.epita.fr">CRI</a>
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

              <!-- Links -->
              <h6 class="text-uppercase font-weight-bold">Contact</h6>
              <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
              <p>
                <i class="fas fa-home mr-3"></i>Kremlin-Bicêtre, Paris 94250</p>
              <p>
                <i class="fas fa-envelope mr-3"></i> epita@epita.fr</p>
              <p>
                <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
              <p>
                <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Footer Links -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->
    {% endblock footer %}
    </div>

    <script src="{% static "js/jquery.min.js" %}" ></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript">
    $(document).on('click', '.confirm', function(){
    return confirm('Are you sure?');
    })
    </script>
    <script type="text/javascript">
        function scrollToAnchor(id){
        $('html,body').animate({scrollTop: $(id).offset().top},'slow');
        }
    </script>
    <script type="text/javascript">
    $(function () {
        {% if anchor %}
            scrollToAnchor($("#" + "{{ anchor }}"));
        {% endif %}
    });
    </script>
    <script>
    function display(el)
    {
        x = document.getElementById(el);
        x.style.display = "block";
    }
    </script>
    {% block script %}{% endblock script %}
</body>
</html>

billeterie_assos/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% load guardian_tags %}

{%block content %}
    <div class="container basic-block">
            <h1 style="
                font-family: 'Courier New', Courier, monospace;
                font-weight:bold;
            ">Dashboard : Ordered by starting date</h1>
            <div class="row">
                <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                    <ul>
                        {% for event in events %}
                        <li>
                            <a style="
                                color:black;
                                opacity:0.8;
                                font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
                                font-size:large;
                                " href="{{event.get_absolute_url}}">{{ event.title }}
                            </a>
                            <p><b>{{event.get_event_state_display}}</b></p>
                        </li>
                        {% endfor %}
                    </ul>
                </article>
            </div>
        </div>
{% endblock content %}

billeterie_assos/templates/event_detail.html
{% extends "base.html" %}
{% load static %}
{% load guardian_tags %}
{% load crispy_forms_tags%}

{%block content %}   
{% get_obj_perms user for event as "event_perms" %}
{% get_obj_perms user for event.assos_id as "asso_perms" %}
<div style="font-size:1.1rem;"class="container basic-block">
    <h1 style="font-family:'Courier New', Courier, monospace; font-weight:bolder; color:#100b2c; text-transform: uppercase; margin:10px; margin-bottom: 30px;">{{event.title}}</h1>
    <div class="row">
        <article style="padding-left:40px;" class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
            {% if perms.event.approve_event %}
                {% if not event.is_approved %}
                <form action="{% url 'event:event_approve' event.pk %}" method="POST">
                    {% csrf_token %}
                <input class="btn btn-outline-success confirm" style="margin-top:10px;" type="submit" value="Approve"/>
                </form>
                {% endif %}
                {% if event.is_validated or event.is_approved %}
                <form action="{% url 'event:event_disapprove' event.pk %}" method="POST">
                    {% csrf_token %}
                <input class="btn btn-outline-danger confirm" style="margin-top:10px;" type="submit" value="Disapprove"/>
                </form>
                {% endif %}
            {% elif "validate_event" in asso_perms %}
                {% if event.is_pending %}
                <form action="{% url 'event:event_validate' event.pk %}" method="POST">
                    {% csrf_token %}
                <input class="btn btn-outline-success confirm" style="margin-top:10px;" type="submit" value="Approve"/>
                </form>
                {% elif event.is_validated %}
                <form action="{% url 'event:event_disapprove' event.pk %}" method="POST">
                    {% csrf_token %}
                <input class="btn btn-outline-danger confirm" style="margin-top:10px;" type="submit" value="Disapprove"/>
                {% endif %}
            {% endif %}
            
            <p><b>State</b> : {{event.get_event_state_display}}</p>
            <p><b>Starting date</b> :
                {{event.start}}
            </p>
            <p><b>Ending date</b> :
                {{event.end}}
            </p>
            <p><b>Address</b> :
                {{event.address_id.raw}}
            </p>
            {% if perms.event.choose_premium %}
            <p><b>Premium</b> :
                {{event.premium_flag}}
            </p>
            {% endif %}
            <p><b>Staffs</b> :
            <ul>
            {% for staff in staffs %}
            <li>{{staff.user.username}}
                {% if "choose_staff" in asso_perms or perms.event.choose_staff %}
                <a style="margin-left:20px; color:#6351ce; font-size:0.8rem;" class="confirm" href="{% url 'event:staff_delete' pk=staff.pk event_pk=event.pk %}">Remove from staff</a>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% if event.see_remaining %}
            <p><b>Tickets left</b> :
            <br/>
            extern : {{extern_left}}
            <br/>
            intern : {{intern_left}}
            <br/>
            staff : {{staff_left}}
            {% endif %}
            <h3 style="padding-top:10px;"><b>Assosciation</b> :
                <a style="margin-left:20px; color:#6351ce;" href="{{event.assos_id.get_absolute_url}}">{{event.assos_id.name}}</a>
            </h3>
            <a href="{% url 'product_detail' event.id %}"><button class="btn btn-outline-info" style="margin-top:10px; margin-bottom: 10px;">Buy Now!</button></a>
            {% if "modify_event" in asso_perms or perms.event.modify_event %}
                <br/>  
                <button id="modify" class="btn btn-outline-info" style="margin-top:10px; margin-bottom: 10px;" onclick="show()">Modify</button>
            {% endif %}
            {% if event.is_ok_cancel and perms.event.cancel_event %}
                <form action="{% url 'event:event_cancel' event.pk %}" method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-danger confirm" style="margin-top:10px;" type="submit" value="Cancel"/>
                </form>
            {% elif event.is_ok_cancelable and "make_event_cancelable" in asso_perms %}
                <form action="{% url 'event:make_cancelable' event.pk %}" method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-danger confirm" style="margin-top:10px;" type="submit" value="Cancel"/>
                </form>
            {% elif event.is_ok_delete %}
                {% if "remove_event" in asso_perms or perms.event.remove_event %}
                <form action="{% url 'event:event_delete' event.pk %}" method="POST">
                {% csrf_token %}
                <input class="btn btn-outline-danger confirm" style="margin-top:10px;" type="submit" value="Delete"/>
                </form>
                {% endif %}
            {% endif %}
            
        </article>
        <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
            <img src={{ event.image.url }} style="
                    opacity: 0.9;
                    height:65%; 
                    width:65%;
                    border-radius: 10px;
                    border: 8px solid black;
                ">
        </article>
        <article id='update' style="{% if not form.errors %} display: none;{% endif %} margin-top:20px;" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
        <h2>Update :</h2><br/>

        <form style="margin-left:40px;" id='my-form' enctype="multipart/form-data" action="{{event.get_absolute_url}}" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-secondary" type="submit" value="Done">
        </form>
    </article>
    </div>
</div>
{% endblock content %}
{% block script %}
    <script type="text/javascript">
        $(document).on('click', "#modify", function(){
            scrollToAnchor("#my-form");
        });
        function show() {
            var x = document.getElementById("update");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
            }
    </script>
    
{% endblock script %}

billeterie_assos/templates/event_list.html
{% extends "base.html" %}
{% load static %}
{% load guardian_tags %}

{%block content %}
    <div class="container basic-block">
            <h1 style="
                font-family: 'Courier New', Courier, monospace;
                font-weight:bold;
            ">Upcoming Events</h1>
            <div class="row">
                <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                    <img src="{% static "img/event_list_img.jpg"%}" style="
                        opacity: 0.9;
                        height:100%; 
                        width:100%;
                        border-radius: 10px;
                    ">
                </article>
                <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                    {% if user.is_authenticated and user.memberships.all %}
                        <a style="margin-bottom:45px;" class="btn btn-danger" href="{% url 'event:general_event_creation' %}">Create an Event</a>
                    {% endif %}
                    {% if events %}
                        <ul>
                        {% for event in events %}
                        {% get_obj_perms user for event as "event_perms" %}
                        {% get_obj_perms user for event.assos_id as "asso_perms" %}
                        <li style="list-style-type: none;
                                    margin-bottom: 5px;
                            ">
                            <a style="
                                color:black;
                                opacity:0.8;
                                font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
                                font-size:large;
                                " href="{{event.get_absolute_url}}">{{ event.title }}
                            </a>
                            {% if event.is_ok_cancel and perms.event.cancel_event %}
                            <a style="margin-left:10px;" class="confirm" href="{% url 'event:event_cancel' event.pk %}">Cancel</a>
                            {% elif event.is_ok_cancelable and "make_event_cancelable" in asso_perms %}
                            <a style="margin-left:10px;" class="confirm" href="{% url 'event:make_cancelable' event.pk %}">Cancel</a>

                            {% endif %}
                            <p style="
                                font-weight: lighter;
                            ">
                                Starting Date: {{ event.start }}
                            </p>
                        </li>
                    {% endfor %}
                    </ul>
                    {% else %}
                        <p> No events </p>
                    {% endif %}
                </article>
            </div>
        </div>
{% endblock content %}

billeterie_assos/templates/event_new.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="basic-block">
    <h1 style="font-family:'Courier New', Courier, monospace; font-weight:bolder; color:#100b2c; text-transform: uppercase; margin:10px; margin-bottom: 30px;">Event Creation</h1>
    <form style="margin-left:50px;" enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-secondary" type="submit" value="Create">
    </form>
</div>
{% endblock content %}

billeterie_assos/templates/my_events.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container basic-block">
        <div class="container">
            <div class="row">
                <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                    <h2 style="font-family: 'Courier New', Courier, monospace;
                                font-weight:bold;
                                margin-bottom: 30px;
                    ">
                        <p style="text-decoration: underline;">My Upcomming Events :</p></h2>
                    {% for event in events %}
                        <li style="list-style-type: none; ">
                            <tr>
                                <a style="font-family: 'Courier New', Courier, monospace;
                                        font-size: 1.7rem;
                                        color: black;
                                " href="{{ event.get_absolute_url}}"
                                >
                                    - {{ event.title }}</a>
                            </tr>
                        </li>
                    {% endfor %}
                </article>
                <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                    <img src= "{% static "img/shop_img.jpg"%}"/ style="
                        height:100%; 
                        width:100%;
                        opacity: 0.9;
                    ">
                </article>
            </div>
        </div>
    </div>
{% endblock %}

billeterie_assos/templates/payment.html
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}

billeterie_assos/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title%}My Profile{% endblock %}

{% block content %}
    <div class="content-section">
        <div class="media" style="margin-top: 50px; margin-bottom:50px;">
            <div class="media-body" style="background-color:white; padding-left:10px;">
                <div style="
                        padding:10px;
                    ">
                    <p style="font-size:2rem;"><b>Username: </b>{{ user.username }}</p>
                    <p class="text-secondary"><b>Birth :</b> {{ user.profile.birth_date }}</p>
                    <p class="text-secondary"><b>Email :</b> {{ user.email }}</p>
                    <p class="text-secondary"><b>Address :</b> 
                        {% if user.address_id %}
                        {{ user.address_id }}
                        {% else %}
                            None
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

billeterie_assos/templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="basic-block">
  <h2 style="margin-top:10px; margin-bottom: 50px;">Sign up</h2>
  <form method="post" style="margin-left:30px;">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-danger" type="submit" style="margin-bottom:40px;">Sign up</button>
  </form>
  <a href="{% url 'login' %}">Already have an account?</a>
</div>
{% endblock %}