billeterie_assos/billeterie_assos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls')), 
    path('', include('shop.urls')),
    url(r'', include('social_django.urls' ,namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billeterie_assos/ecommerce_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('ship/', views.index, name='index'),
    path('product/<int:product_id>/<slug:product_slug>/',
        views.show_product, name='product_detail'),
    path('cart/', views.show_cart, name='show_cart'),
    path('checkout/', views.checkout, name='checkout'),
]

billeterie_assos/event/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from social_django.urls import urlpatterns as social_django_urls
from shop import views as com_views
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('assos/mine/', login_required(views.MyAssosView.as_view(), login_url='login'), name='my_assos'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('cri_epita.urls', namespace="cri")),
    path('assos/<int:pk>', views.AssosDetailView.as_view(), name='asso_detail'),
    path('assos/', views.AssosView.as_view(), name='assos'),
    path('event/', views.EventListView.as_view(), name='events'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('upcomming_events/', views.Upcomming_Events, name='upcomming_events'),
    path('assos/delete/<int:pk>', views.AssosDelete.as_view(), name='assos_delete'),
    path('assos/<int:asso_pk>/delete/member/<int:pk>', views.MemberDelete.as_view(), name='delete_member'),
    path('assos/<int:asso_pk>/manager/add/<int:pk>', views.ManagerCreate.as_view(), name='add_manager'),
    path('assos/<int:asso_pk>/delete/manager/<int:pk>', views.ManagerDelete.as_view(), name='delete_manager'),
    path('shop/', com_views.index_shop, name='shop'),
    path('product/<int:product_id>/', com_views.show_product, name='product_detail'),
    path('search/', views.search, name='search'),
    path('assos/create/', permission_required('event.add_association', login_url='login')(views.AssosCreateView.as_view()), name='asso_creation'),
    path('assos/event/create/', views.EventCreateGeneralView.as_view(), name='general_event_creation'),
    path('assos/event/create/<int:asso>', views.EventCreateView.as_view(), name='event_creation'),
    path('event/delete/<int:pk>', views.EventDelete.as_view(), name='event_delete'),
    path('event/cancelable/<int:pk>', views.EventCancelable.as_view(), name='make_cancelable'),
    path('event/cancel/<int:pk>', views.EventCancel.as_view(), name='event_cancel'),
    path('assos/president/add/<int:pk>', permission_required('event.add_president', login_url='login')(views.PresidentCreate.as_view()), name='add_president'),
    path('event/<int:event_pk>/staff/delete/<int:pk>', views.StaffDelete.as_view(), name='staff_delete'),
    path('event/approve/<int:pk>', views.EventApprove.as_view(), name='event_approve'),
    path('event/validate/<int:pk>', views.EventValidate.as_view(), name='event_validate'),
    path('event/pending/<int:pk>', views.EventDisapprove.as_view(), name='event_disapprove'),
    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),
]

billeterie_assos/shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    
    path('shop', views.index_shop, name='index_shop'),
    path('product/<int:product_id>/',
        views.show_product, name='product_detail'),
    path('cart/', views.show_cart, name='show_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('info/', views.info, name='info'),
]

billeterie_assos/ecommerce_app/views.py
from django.shortcuts import render, HttpResponse, redirect, \
    get_object_or_404, reverse
from django.contrib import messages
from .models import Product, Order, LineItem
from .forms import CartForm, CheckoutForm
from . import cart

# Create your views here.


def index(request):
    all_products = Product.objects.all()
    return render(request, "ecommerce_app/index.html", {
                                    'all_products': all_products,
                                    })


def show_product(request, product_id, product_slug):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = CartForm(request, request.POST)
        if form.is_valid():
            request.form_data = form.cleaned_data
            cart.add_item_to_cart(request)
            return redirect('show_cart')

    form = CartForm(request, initial={'product_id': product.id})
    return render(request, 'ecommerce_app/product_detail.html', {
                                            'product': product,
                                            'form': form,
                                            })


def show_cart(request):

    if request.method == 'POST':
        if request.POST.get('submit') == 'Update':
            cart.update_item(request)
        if request.POST.get('submit') == 'Remove':
            cart.remove_item(request)

    cart_items = cart.get_all_cart_items(request)
    cart_subtotal = cart.subtotal(request)
    return render(request, 'ecommerce_app/cart.html', {
                                            'cart_items': cart_items,
                                            'cart_subtotal': cart_subtotal,
                                            })


def checkout(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            o = Order(
                name = cleaned_data.get('name'),
                email = cleaned_data.get('email'),
                postal_code = cleaned_data.get('postal_code'),
                address = cleaned_data.get('address'),
            )
            o.save()

            all_items = cart.get_all_cart_items(request)
            for cart_item in all_items:
                li = LineItem(
                    product_id = cart_item.product_id,
                    price = cart_item.price,
                    quantity = cart_item.quantity,
                    order_id = o.id
                )

                li.save()

            cart.clear(request)

            request.session['order_id'] = o.id

            messages.add_message(request, messages.INFO, 'Order Placed!')
            return redirect('checkout')


    else:
        form = CheckoutForm()
        return render(request, 'ecommerce_app/checkout.html', {'form': form})

billeterie_assos/ecommerce_app/templates/ecommerce_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}Simple ecommerce </title>
    <style>
        table{
            border-collapse: collapse;
            border: none;
        }
        td{
            padding: 10px;
        }
        form{
            margin-bottom: 0;
        }
    </style>
</head>
<body>

<p>
    <a href="{% url 'event:index' %}">All Products</a> 
    <a href="{% url 'event:show_cart' %}">Cart: {{ cart_item_count }} item</a>
</p>

{% block content %}

{% endblock %}

</body>
</html>

billeterie_assos/ecommerce_app/templates/ecommerce_app/cart.html
{% extends 'ecommerce_app/base.html' %}

{% block title %}
    My Cart |
{% endblock %}

{% block content %}

    <h2>My Cart</h2>
    
    {% if cart_item_count %}
    <table>
        <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th></th>
            <th></th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart_items %}
            <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.price }}</td>
                <td>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="text" name="quantity" value="{{ item.quantity }}">
                        <input type="hidden" name="item_id" value="{{ item.id }}">
                </td>
                <td>
                        <input type="submit" name="submit" value="Update">
                    </form>
                </td>
                <td>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="item_id" value="{{ item.id }}">
                        <input type="submit" name="submit" value="Remove">
                    </form>
                </td>
                <td>${{ item.total_cost }}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" style="text-align: right">Total</td>
                <td>${{ cart_subtotal }}</td>
            </tr>
            <tr>
                <td></td>
                <td colspan="4" style="text-align: right">
                    <a href="{% url 'index' %}" class="btn btn-primary">Continue Shopping</a>
                </td>
                {% if cart_item_count %}
                    <td><a href="{% url 'checkout' %}" class="btn btn-primary">Checkout</a></td>
                {% endif %}
            </tr>
        </tfoot>
    </table>
    {% else %}
        <p>Cart Empty</p>
    {% endif %}


{% endblock %}

billeterie_assos/ecommerce_app/templates/ecommerce_app/checkout.html
{% extends 'ecommerce_app/base.html' %}

{% block title %}
    Checkout |
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">

            <h2>Checkout</h2>

            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}


            <form action="" method="post">
                <table>
                    {% csrf_token %}
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Place Order"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

{% endblock %}

billeterie_assos/ecommerce_app/templates/ecommerce_app/index.html
{% extends 'ecommerce_app/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <h2>Available Products</h2>

            {% for product in all_products %}
                <div class="col-lg-4">
                    <h3><a href="{% url 'event:product_detail' product.pk product.slug %}">{{ product.name }}</a></h3>
                    <p>Price ${{ product.price }}</p>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

billeterie_assos/ecommerce_app/templates/ecommerce_app/product_detail.html
{% extends 'ecommerce_app/base.html' %}

{% block title %}
    {{ product.name }} |
{% endblock %}


{% block content %}

    <div class="container">
        <div class="row">

            <p><a href="{% url 'index' %}">All Products </a> &gt;
                {{ product.name }}
            </p>

                <h2>{{ product.name }}</h2>
                <p>Price ${{ product.price }}</p>

                <form action="{% url 'product_detail' product.id product.slug %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Add to cart" class="btn btn-primary" >
                </form>

        </div>

    </div>

{% endblock %}