billeterie_assos/billeterie_assos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls')), 
    path('', include('shop.urls')),
    url(r'', include('social_django.urls' ,namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billeterie_assos/shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    
    path('shop', views.index_shop, name='index_shop'),
    path('product/<int:product_id>/',
        views.show_product, name='product_detail'),
    path('cart/', views.show_cart, name='show_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('info/', views.info, name='info'),
]

billeterie_assos/shop/models.py
from django.db import models
from event.models import Price
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=191)
    event_id = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=7, decimal_places=2) 
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to='products_images/', blank=True)
     
    def __str__(self):
        return self.name


class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=100)
    ticket_type = models.CharField(max_length=50)

    def __str__(self):
        return "{}:{}".format(self.product.name, self.id)

    def update_quantity(self, quantity):
        self.quantity = self.quantity + quantity
        self.save()

    def total_cost(self):
        return self.quantity * self.price


class Order(models.Model):
    name = models.CharField(max_length=191)
    email = models.EmailField()
    postal_code = models.IntegerField()
    address = models.CharField(max_length=191)
    date = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)
    ticket_id = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return "{}:{}".format(self.id, self.email)

    def total_cost(self):
        return sum([ li.cost() for li in self.lineitem_set.all() ] )


class LineItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}:{}".format(self.product.name, self.id)

    def cost(self):
        return self.price * self.quantity

billeterie_assos/shop/forms.py
from django import forms
from .models import Order
class CartForm(forms.Form):
    quantity = forms.IntegerField(initial='1', min_value=1, max_value=5)
    product_id = forms.IntegerField(widget=forms.HiddenInput)
    CHOICES = ((0, 'Internal'),(1, 'External'), (2, 'Staff'))
    price = forms.ChoiceField(choices=CHOICES)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(CartForm, self).__init__(*args, **kwargs)


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('paid', 'ticket_id', 'user',)

        widgets = {
            'address': forms.Textarea(attrs={'row': 5, 'col': 8}),
        }

billeterie_assos/shop/views.py
from django.shortcuts import render, HttpResponse, redirect, \
    get_object_or_404, reverse
from django.contrib import messages
from .models import Product, Order, LineItem
from .forms import CartForm, CheckoutForm
from . import cart
from event import views
from event import models
from django.db.models import ProtectedError
from django.db import models as models_email
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
import qrcode
from django.core.mail.backends.smtp import EmailBackend
from django.core.mail.message import EmailMessage
from django.core import mail
from django.core.mail import get_connection
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.conf import settings

# Create your views here.
    
def index_shop(request):
    all_products = Product.objects.all()
    users = User.objects.all()
    user_type = "E"

    for user in users:
        at_pos = user.email.find("@")
        start_email = user.email[:at_pos]
        end_email = user.email[at_pos:]
       
        if start_email == str(request.user) and end_email[:9] == "@epita.fr":
            user_type = "I"         
        
        
    for event in views.EventListView.get_queryset(request):
        my_price = 0
        all_price = event.prices.all()
        try:
            my_price = all_price.get(ticket_type=user_type).price
        except models.Price.DoesNotExist:        
            my_price = 0

        try:
            product = all_products.get(id=event.id)
            product.price = my_price
            product.save()
        except Product.DoesNotExist:        
            product = Product(name = event.title,price = my_price,id = event.id)
            product.save()

    
    for product in all_products:
        try:
            event = views.EventListView.get_queryset(request).get(id=product.id)
        except models.Event.DoesNotExist:
            remove_product(request, product.id)

    all_products = Product.objects.all()
    return render(request, "index_shop.html", {
                                    'all_products': all_products,
                                    })


def send_mail_ticket(request, subject, body, to):
    email = EmailMessage()
    email.subject = subject
    email.body = body
    email.to = [to]
    #email.attach_file("/home/romain/Downloads/clement.davin.jpeg")
    email.connection = get_connection()
    return email.send()

def show_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    event_prices = views.EventListView.get_queryset(request).get(id=product.id).prices.all()
    
    all_tickets = models.Ticket.objects.filter(event_id=product_id)
    external_left = 0
    internal_left = 0
    staff_left = 0
    for ticket in all_tickets:
        try:
            ticket.purchase
        except models.Purchase.DoesNotExist:
            if ticket.ticket_type == models.Ticket.EXTERN:
                external_left += 1
            if ticket.ticket_type == models.Ticket.INTERN:
                internal_left += 1
            if ticket.ticket_type == models.Ticket.STAFF:
                staff_left += 1

    ext = "Extern"
    inter = "Intern"
    staff = "Staff"

    if external_left == 0:
        ext = ""
    if internal_left == 0:
        inter = ""
    if staff_left == 0:
        staff = ""

    if staff_left == 0 and internal_left == 0 and external_left == 0:
        inter = "No Tickets available for this event"

    if request.method == 'POST':
        form = CartForm(request, request.POST, product_id)
        if form.is_valid():
            request.form_data = form.cleaned_data
            cart.add_item_to_cart(request)
            return redirect('show_cart')

    form = CartForm(request, initial={'product_id': product.id})
    return render(request, 'product_detail.html', {
                                            'product': product,
                                            'form': form,
                                            'prices':event_prices,
                                            'ext' : ext,
                                            'int' : inter,
                                            'staff' : staff
                                            })

 
def remove_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        product.delete()  
    except ProtectedError:
        error_message = "This object can't be deleted!!\n\n\n"

def show_cart(request):
    if request.method == 'POST':
        if request.POST.get('submit') == 'Update':
            cart.update_item(request)
        if request.POST.get('submit') == 'Remove':
            cart.remove_item(request)

    cart_items = cart.get_all_cart_items(request)
    cart_subtotal = cart.subtotal(request)
    return render(request, 'cart.html', {
                                            'cart_items': cart_items,
                                            'cart_subtotal': cart_subtotal,
                                            })


def checkout(request):
    price = cart.subtotal(request)
    #cart.qrcode(request)
    return render(request, 'checkout.html', {'price': price})

def info(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = User.objects.get(id=request.user.id)
            my_tickets = views.Purchase.objects.filter(user=user)
            for my_ticket in my_tickets:
                try:
                    Order.objects.get(ticket_id=my_ticket.ticket_id.id)
                except Order.DoesNotExist:
                    o = Order(
                        name = cleaned_data.get('name'),
                        email = cleaned_data.get('email'),
                        postal_code = cleaned_data.get('postal_code'),
                        address = cleaned_data.get('address'),
                        ticket_id = my_ticket.ticket_id.id,
                        user = user
                    )
                    o.save()
                    request.session['order_id'] = o.id
                    send_mail_ticket(request, "Ticket Buy !", "Thanks for Buying this ticket ! your ticket's id is : " + str(my_ticket.ticket_id.id), o.email)

            cart.clear(request)

            messages.add_message(request, messages.INFO, 'Order Placed!')
        return redirect('info')


    else:
        form = CheckoutForm()
        return render(request, 'info_checkout.html', {'form': form})

billeterie_assos/shop/templates/cart.html
{% extends 'base.html' %}

{% block title %}
    My Cart |
{% endblock %}

{% block content %}

    <div class="container basic-block">
        <h2>My Cart</h2>
        
        {% if cart_item_count %}
        <table>
            <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th></th>
                <th></th>
                <th>Total</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart_items %}
                <tr>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="item_id" value="{{ item.id }}">
                    </td>
                    <td>
                        </form>
                    </td>
                    <td>
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="item_id" value="{{ item.id }}">
                            <input type="submit" name="submit" value="Remove">
                        </form>
                    </td>
                    <td>${{ item.total_cost }}</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" style="text-align: right; padding-bottom:10px;">Total</td>
                    <td>${{ cart_subtotal }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td colspan="4" style="text-align: right">
                        <a href="{% url 'index_shop' %}" class="btn btn-primary">Continue Shopping</a>
                    </td>
                    {% if cart_item_count %}
                        <td><a href="{% url 'checkout' %}" class="btn btn-primary">Checkout</a></td>
                    {% endif %}
                </tr>
            </tfoot>
        </table>
        {% else %}
            <p>Cart Empty</p>
        {% endif %}
    </div>


{% endblock %}

billeterie_assos/shop/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
<div class="container basic-block">
        <h3><b style="text-decoration: underline;">Payment</b> :</h3>
        <br> </br>
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type= "hidden" name="cmd" value="_xclick" id="id_cmd">
        <input type= "hidden" name="charset" value="utf-8" id="id_charset">
        <input type= "hidden" name="currency_code" value ="EUR" id="id_currency_code">
        <input type= "hidden" name="no_shipping" value ="1" id="id_no_shipping">
        <input type= "hidden" name="business" value ="association.epita@gmail.com" id="id_business">
        <input type= "hidden" name="amount" value ={{price}} id="id_amount">
        <input type= "hidden" name="item_name" value ="Events" id="id_item_name">
        <input type= "hidden" name="invoice" value="unique-invoice-id" id="id_invoice">
        <input type= "hidden" name="return" value ="http://localhost:8000/info" id="id_return">
        <input type= "hidden" name="cancel_return" value ="http://localhost:8000/" id="id_cancel_return">
        <input type= "hidden" name="custom" value="premium_plan" id="id_custom">
        <input type= "image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal, le réflexe sécurité pour payer en ligne">
        <img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
        </form>
    </div>
{% endblock %}

billeterie_assos/shop/templates/index_shop.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container basic-block">
        <div class="container">
            <div class="row">
                <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                    <h2 style="font-family: 'Courier New', Courier, monospace;
                                font-weight:bold;
                    ">
                        Available Products</h2>
                    <ul style="margin-left: 35%;">
                    {% for product in all_products %}
                        <li>
                            <tr>
                                <h3 style="font-family: 'Courier New', Courier, monospace;
                                        font-style: italic;
                                ">
                                    {{ product.name }}</h3>
                                    <p style="padding-left: 20px;">Price: €{{ product.price }}
                                        <a href="{% url 'product_detail' product.pk %}" class="btn btn-warning"
                                        style="opacity: 0.9;
                                                margin-left: 20%"
                                    >Buy</a>
                                    </p>
                            </tr>
                        </li>
                    {% endfor %}
                    </ul>
                </article>
                <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">
                    <img src= "{% static "img/shop_img.jpg"%}"/ style="
                        height:100%; 
                        width:100%;
                        opacity: 0.9;
                    ">
                </article>
            </div>
        </div>
    </div>
{% endblock %}

billeterie_assos/shop/templates/info_checkout.html
{% extends 'base.html' %}                                                       
                                                                                
{% load static %}                                                               
{% block title %}                                                               
    Checkout |                                                                  
{% endblock %}                                                                  
                                                                                
{% block content %}                                                             
                                                                                
    <div class="container basic-block">                                                                          
        <h2 style="font-family: 'Courier New', Courier, monospace;              
        font-weight:bold;                                                       
        ">Checkout</h2>                                                         
        <div class="row">                                                       
            <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">               
                {% for message in messages %}                                   
                    <p>{{ message }}</p>                                        
                {% endfor %}                                                    
                <form action="" method="post">                                  
                    <table>                                                     
                        {% csrf_token %}                                        
                        {{ form.as_table }}                                     
                        <tr>                                                    
                            <td></td>                                           
                            <td><input type="submit" class="btn btn-info" value="Place Order"></td>
                        </tr>                                                   
                    </table>                                                    
                </form>                                                         
            </article>                                                          
            <article class="col-xs-4 col-sm-4 col-md-4 col-lg-6">               
                <img src="{% static "img/checkout_img.png"%}" style="           
                    opacity: 0.9;                                               
                    height:100%;                                                
                    width:100%;                                                 
                    border-radius: 10px;                                        
                ">                                                              
            </article>                                                          
        </div>                                                                  
    </div>                                                                      
                                                                                
{% endblock %}

billeterie_assos/shop/templates/product_detail.html
{% extends 'base.html' %}


{% block title %}
    {{ product.name }} |
{% endblock %}


{% block content %}

    <div class="container basic-block">
            <p><a href="{% url 'index_shop' %}" style="color: black; text-decoration: underline;">All Products </a> &gt;
                {{ product.name }}
            </p>
                <h2 style="font-family: 'Courier New', Courier, monospace;
                font-weight:bold;
                ">
                    {{ product.name }}
                </h2>
                <div style="
                    margin-left:10%;
                ">
                    {% if prices %}
                    <p>
                        {% for price in prices %} 
                            {{ price.get_ticket_type_display }}: {{ price.price }}€<br/>
                        {% endfor %}
                    </p>
                        <p style="
                            font-style: italic;
                        ">
                            Avaiable tickets: {{int}} {{ext}} {{staff}}
                        </p>


                        <form action="{% url 'product_detail' product.pk %}" 
                                                method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <input type="submit" value="Add to cart" class="btn btn-primary" >
                        </form>
                    {% else %}
                        <p> No Tickets To Sell </p>
                    {% endif %}
                </div>
    </div>
{% endblock %}