billeterie_assos/billeterie_assos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls')), 
    path('', include('shop.urls')),
    url(r'', include('social_django.urls' ,namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billeterie_assos/event/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from social_django.urls import urlpatterns as social_django_urls
from shop import views as com_views
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('assos/mine/', login_required(views.MyAssosView.as_view(), login_url='login'), name='my_assos'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('cri_epita.urls', namespace="cri")),
    path('assos/<int:pk>', views.AssosDetailView.as_view(), name='asso_detail'),
    path('assos/', views.AssosView.as_view(), name='assos'),
    path('event/', views.EventListView.as_view(), name='events'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('upcomming_events/', views.Upcomming_Events, name='upcomming_events'),
    path('assos/delete/<int:pk>', views.AssosDelete.as_view(), name='assos_delete'),
    path('assos/<int:asso_pk>/delete/member/<int:pk>', views.MemberDelete.as_view(), name='delete_member'),
    path('assos/<int:asso_pk>/manager/add/<int:pk>', views.ManagerCreate.as_view(), name='add_manager'),
    path('assos/<int:asso_pk>/delete/manager/<int:pk>', views.ManagerDelete.as_view(), name='delete_manager'),
    path('shop/', com_views.index_shop, name='shop'),
    path('product/<int:product_id>/', com_views.show_product, name='product_detail'),
    path('search/', views.search, name='search'),
    path('assos/create/', permission_required('event.add_association', login_url='login')(views.AssosCreateView.as_view()), name='asso_creation'),
    path('assos/event/create/', views.EventCreateGeneralView.as_view(), name='general_event_creation'),
    path('assos/event/create/<int:asso>', views.EventCreateView.as_view(), name='event_creation'),
    path('event/delete/<int:pk>', views.EventDelete.as_view(), name='event_delete'),
    path('event/cancelable/<int:pk>', views.EventCancelable.as_view(), name='make_cancelable'),
    path('event/cancel/<int:pk>', views.EventCancel.as_view(), name='event_cancel'),
    path('assos/president/add/<int:pk>', permission_required('event.add_president', login_url='login')(views.PresidentCreate.as_view()), name='add_president'),
    path('event/<int:event_pk>/staff/delete/<int:pk>', views.StaffDelete.as_view(), name='staff_delete'),
    path('event/approve/<int:pk>', views.EventApprove.as_view(), name='event_approve'),
    path('event/validate/<int:pk>', views.EventValidate.as_view(), name='event_validate'),
    path('event/pending/<int:pk>', views.EventDisapprove.as_view(), name='event_disapprove'),
    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),
]

billeterie_assos/shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    
    path('shop', views.index_shop, name='index_shop'),
    path('product/<int:product_id>/',
        views.show_product, name='product_detail'),
    path('cart/', views.show_cart, name='show_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('info/', views.info, name='info'),
]

billeterie_assos/templates/includes/mainmenu.html
{% load static %}

<!--Navbar-->
<nav class="navbar navbar-dark navbar-expand-lg navbar-style">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a style="height:5%; width:5%; margin-right:5px;" href="{% url 'event:index' %}"><img src="{% static "img/logo-epita.png" %}" style="height:80%; width:80%; margin-right:5px;"></a>

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'event:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'event:assos' %}">Associations</a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'event:events' %}">Events</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {{user.username}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'event:profile' %}">My profile</a>
          <a class="dropdown-item" href="{% url 'event:my_assos' %}">My associations</a>
          <a class="dropdown-item" href="{% url 'show_cart' %}">My cart</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'event:upcomming_events' %}">My upcoming events</a>
          <a class="dropdown-item" href="{% url 'event:dashboard' %}">Dashboard</a>
        </div>
      </li>
    {% else %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">My space</a>
      </li>
    {% endif %}
    </ul>
     <form id="searchform" action="{% url 'event:search' %}" method="get" accept-charset="utf-8">
         <input class="searchfield" id="searchbox" name="search_bar" type="text" placeholder="Search">
         <button class="btn btn-outline-success my-2 my-sm-0 btn-nav" type="submit">Search</button>
        <i class="fa fa-search"></i>
      </button>
    </form>
    {% if user.is_authenticated %} 
        <a href="{% url 'logout' %}"><button class="btn btn-outline-success my-2 my-sm-0 btn-nav">Logout</button></a>
    {% else %}
        <a href="{% url 'login' %}"><button class="btn btn-outline-success my-2 my-sm-0 btn-nav">Login</button></a>
    {% endif %}

      {% if user.is_authenticated %}
        <a href="{% url 'event:shop' %}"><button class="btn btn-outline-success my-2 my-sm-0 btn-nav">Shop</button></a>
    {% else %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Shop</a>
      </li>
    {% endif %}

  </div>
</nav>